name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["latest_branch"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Deploy to GitHub Pages
        run: git push origin ["latest_branch"]
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          publish_dir: |
            ./src/main/resources/css
            ./src/main/resources/images
            ./src/main/resources/js
            ./src/main/resources/templates/fragments
            ./src/main/resources/templates
